In [1]:
import pandas as pd


df = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\application_train.csv")

df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='str', length=122)

In [4]:
len(df)

307511

In [9]:
df_description = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\HomeCredit_columns_description.csv" , encoding="unicode_escape")


df_description.head()

,Unnamed: 0,Table,Row,Description,Special
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN

In [11]:
for ix , row in df_description.iterrows():

    print(f"In the {row["Table"]} table the {row["Row"] } means : {row["Description"]} ")
    print("\n\n")

In the application_{train|test}.csv table the SK_ID_CURR means : ID of loan in our sample



In the application_{train|test}.csv table the TARGET means : Target variable (1 - client with payment difficulties: he/she had late payment more than X days on at least one of the first Y installments of the loan in our sample, 0 - all other cases)



In the application_{train|test}.csv table the NAME_CONTRACT_TYPE means : Identification if loan is cash or revolving



In the application_{train|test}.csv table the CODE_GENDER means : Gender of the client



In the application_{train|test}.csv table the FLAG_OWN_CAR means : Flag if the client owns a car



In the application_{train|test}.csv table the FLAG_OWN_REALTY means : Flag if client owns a house or flat



In the application_{train|test}.csv table the CNT_CHILDREN means : Number of children the client has



In the application_{train|test}.csv table the AMT_INCOME_TOTAL means : Income of the client



In the application_{train|test}.csv table the AMT_CREDIT means : Credit amount of the loan



In the application_{train|test}.csv table the AMT_ANNUITY means : Loan annuity



In the application_{train|test}.csv table the AMT_GOODS_PRICE means : For consumer loans it is the price of the goods for which the loan is given



In the application_{train|test}.csv table the NAME_TYPE_SUITE means : Who was accompanying client when he was applying for the loan



In the application_{train|test}.csv table the NAME_INCOME_TYPE means : Clients income type (businessman, working, maternity leave,)



In the application_{train|test}.csv table the NAME_EDUCATION_TYPE means : Level of highest education the client achieved



In the application_{train|test}.csv table the NAME_FAMILY_STATUS means : Family status of the client



In the application_{train|test}.csv table the NAME_HOUSING_TYPE means : What is the housing situation of the client (renting, living with parents, ...)



In the application_{train|test}.csv table the REGION_POPULATION_RELATIVE means : Normalized population of region where client lives (higher number means the client lives in more populated region)



In the application_{train|test}.csv table the DAYS_BIRTH means : Client's age in days at the time of application



In the application_{train|test}.csv table the DAYS_EMPLOYED means : How many days before the application the person started current employment



In the application_{train|test}.csv table the DAYS_REGISTRATION means : How many days before the application did client change his registration



In the application_{train|test}.csv table the DAYS_ID_PUBLISH means : How many days before the application did client change the identity document with which he applied for the loan



In the application_{train|test}.csv table the OWN_CAR_AGE means : Age of client's car



In the application_{train|test}.csv table the FLAG_MOBIL means : Did client provide mobile phone (1=YES, 0=NO)



In the application_{train|test}.csv table the FLAG_EMP_PHONE means : Did client provide work phone (1=YES, 0=NO)



In the application_{train|test}.csv table the FLAG_WORK_PHONE means : Did client provide home phone (1=YES, 0=NO)



In the application_{train|test}.csv table the FLAG_CONT_MOBILE means : Was mobile phone reachable (1=YES, 0=NO)



In the application_{train|test}.csv table the FLAG_PHONE means : Did client provide home phone (1=YES, 0=NO)



In the application_{train|test}.csv table the FLAG_EMAIL means : Did client provide email (1=YES, 0=NO)



In the application_{train|test}.csv table the OCCUPATION_TYPE means : What kind of occupation does the client have



In the application_{train|test}.csv table the CNT_FAM_MEMBERS means : How many family members does client have



In the application_{train|test}.csv table the REGION_RATING_CLIENT means : Our rating of the region where client lives (1,2,3)



In the application_{train|test}.csv table the REGION_RATING_CLIENT_W_CITY means : Our rating of the region where client lives with taking city into account (1,2,3)



In the application_{train|test}.csv table the WEEKDAY_APPR_PROCESS_START means : On which day of the week did the client apply for the loan



In the application_{train|test}.csv table the HOUR_APPR_PROCESS_START means : Approximately at what hour did the client apply for the loan



In the application_{train|test}.csv table the REG_REGION_NOT_LIVE_REGION means : Flag if client's permanent address does not match contact address (1=different, 0=same, at region level)



In the application_{train|test}.csv table the REG_REGION_NOT_WORK_REGION means : Flag if client's permanent address does not match work address (1=different, 0=same, at region level)



In the application_{train|test}.csv table the LIVE_REGION_NOT_WORK_REGION means : Flag if client's contact address does not match work address (1=different, 0=same, at region level)



In the application_{train|test}.csv table the REG_CITY_NOT_LIVE_CITY means : Flag if client's permanent address does not match contact address (1=different, 0=same, at city level)



In the application_{train|test}.csv table the REG_CITY_NOT_WORK_CITY means : Flag if client's permanent address does not match work address (1=different, 0=same, at city level)



In the application_{train|test}.csv table the LIVE_CITY_NOT_WORK_CITY means : Flag if client's contact address does not match work address (1=different, 0=same, at city level)



In the application_{train|test}.csv table the ORGANIZATION_TYPE means : Type of organization where client works



In the application_{train|test}.csv table the EXT_SOURCE_1 means : Normalized score from external data source



In the application_{train|test}.csv table the EXT_SOURCE_2 means : Normalized score from external data source



In the application_{train|test}.csv table the EXT_SOURCE_3 means : Normalized score from external data source



In the application_{train|test}.csv table the APARTMENTS_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the BASEMENTAREA_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the YEARS_BEGINEXPLUATATION_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the YEARS_BUILD_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the COMMONAREA_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the ELEVATORS_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the ENTRANCES_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the FLOORSMAX_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the FLOORSMIN_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LANDAREA_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LIVINGAPARTMENTS_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LIVINGAREA_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the NONLIVINGAPARTMENTS_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the NONLIVINGAREA_AVG means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the APARTMENTS_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the BASEMENTAREA_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the YEARS_BEGINEXPLUATATION_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the YEARS_BUILD_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the COMMONAREA_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the ELEVATORS_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the ENTRANCES_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the FLOORSMAX_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the FLOORSMIN_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LANDAREA_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LIVINGAPARTMENTS_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LIVINGAREA_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the NONLIVINGAPARTMENTS_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the NONLIVINGAREA_MODE means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the APARTMENTS_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the BASEMENTAREA_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the YEARS_BEGINEXPLUATATION_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the YEARS_BUILD_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the COMMONAREA_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the ELEVATORS_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the ENTRANCES_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the FLOORSMAX_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the FLOORSMIN_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LANDAREA_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LIVINGAPARTMENTS_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor



In the application_{train|test}.csv table the LIVINGAREA_MEDI means : Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor




In [13]:
df["SK_ID_CURR"][0]

np.int64(100002)

In [15]:
df_bureau = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\bureau.csv")

df_bureau.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [17]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='str', length=122)

In [19]:
count = 0
for bureau_column in df_bureau.columns:

    if bureau_column in df.columns:
        print("OK")

    else:
        print("Count of not okey is " ,count)
        count +=1

OK
Count of not okey is  0
Count of not okey is  1
Count of not okey is  2
Count of not okey is  3
Count of not okey is  4
Count of not okey is  5
Count of not okey is  6
Count of not okey is  7
Count of not okey is  8
Count of not okey is  9
Count of not okey is  10
Count of not okey is  11
Count of not okey is  12
Count of not okey is  13
Count of not okey is  14
OK

In [20]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='str', length=122)

In [21]:
df_bureau.columns

Index(['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY',
       'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE',
       'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG',
       'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT',
       'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE',
       'AMT_ANNUITY'],
      dtype='str')

In [ ]:
import numpy as np

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
675684,100002,6158904,Closed,currency 1,-1125,0,-1038.0,-1038.0,NaN,0,40761.000,NaN,NaN,0.0,Credit card,-1038,0.0
675685,100002,6158905,Closed,currency 1,-476,0,NaN,-48.0,NaN,0,0.000,0.0,NaN,0.0,Credit card,-47,NaN
675686,100002,6158906,Closed,currency 1,-1437,0,-1072.0,-1185.0,0.000,0,135000.000,0.0,0.000,0.0,Consumer credit,-1185,0.0
675687,100002,6158907,Closed,currency 1,-1121,0,-911.0,-911.0,3321.000,0,19071.000,NaN,NaN,0.0,Consumer credit,-906,0.0
675688,100002,6158908,Closed,currency 1,-645,0,85.0,-36.0,5043.645,0,120735.000,0.0,0.000,0.0,Consumer credit,-34,0.0
675689,100002,6158909,Active,currency 1,-103,0,NaN,NaN,40.500,0,31988.565,0.0,31988.565,0.0,Credit card,-24,0.0
1337779,100002,6158903,Active,currency 1,-1042,0,780.0,NaN,NaN,0,450000.000,245781.0,0.000,0.0,Consumer credit,-7,0.0
1486113,100002,6113835,Closed,currency 1,-1043,0,62.0,-967.0,0.000,0,67500.000,NaN,NaN,0.0,Credit card,-758,0.0

In [ ]:
df_bureau = pd.read_csv("")

8